config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'sign-up' }

  get 'about/index'

  get 'contact/index'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/secure_controller.rb
class SecureController < ApplicationController
  before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, http_method=nil)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      if http_method
        link_to(link_text, link_path, method: http_method)
      else
        link_to(link_text, link_path)
      end
    end
  end
end

app/views/about/index.html.slim
h1 About us

p We are building a sophisticated B2B platform that will enable travel agents and tour operators in the Greater Mekong region in a faster, more convenient and digitalized way to conduct business with each other across borders.
p Our research showed that it is difficult to have choices for different tour quotations in South East Asia.
p We want the businesses to connect with each other much easier, giving more choices and a faster way to do business.
p To achieve this goal we will create a platform with integrated document management, video/text-messenger, rating system and digital invoicing.

app/views/admin/index.html.slim
h1 Admin#index
p Find me in app/views/admin/index.html.slim

app/views/contact/index.html.slim
.row
  .col-md-12
    h1 Get in touch
.row
  .col-xs-6.col-md-3
    a.thumbnail href="#" mailto="cyber8kh@gmail.com"
      img src="https://goo.gl/ROOZi9" alt="Rithy Bonaparte" class="img-circle"
    ul.list-group
      li.list-group-item Rithy Bonaparte
      li.list-group-item cyber8kh@gmail.com

app/views/home/index.html.slim
.jumbotron
  h1 Manoa - ម្នាស់
  p.lead Manoa is the Khmer word for pineapple. This fruit is found all over South-East-Asia and is commonly found at all markets. welcome to manoa ! from travel agent to travel agent make more easy.
  p.lead For us, Manoa stand for the people in the region. We want to bring them together, by enabling regional traveling businesses to connect to each other faster, easier and safer.
  p.label.label-info Interested? We are looking for early adopters to join our beta-test.

app/views/layouts/_footer.html.slim
footer.footer
  p © 2016 Manoa.

app/views/layouts/_header.html.slim
.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}" Manoa
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav
        = nav_link('Home', root_path)
        = nav_link('About', about_index_path)
        = nav_link('Contact', contact_index_path)
      ul.nav.navbar-nav.navbar-right
        - if !user_signed_in?
          = nav_link('Login', new_user_session_path)
          = nav_link('Sign up', new_user_registration_path)
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false"
              = current_user.email
              span.caret
            ul.dropdown-menu role="menu"
              li
                a href="#" My Profile
              li
                a href="#" My Company
              li.divider
              = nav_link('Sign Out', destroy_user_session_path, :delete)
      / form.navbar-form.navbar-left role="search"
      /   div.form-group
      /     input.form-control type="text" placeholder="Search"
      /   button type="submit" class="btn btn-default" Submit

app/views/layouts/application.html.slim
html
  head
    title Manoa
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'